name: Auto Fix with Codex

on:
  workflow_run:
    workflows: ["CI"]   # あなたの pytest ワークフロー名に合わせる
    types:
      - completed

jobs:
  codex-fix:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -e .[test]

      - name: Run pytest and capture log
        run: |
          pytest -q > error.log 2>&1 || true
          cat error.log

      - name: Call Codex to generate patch
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          openai api chat.completions.create \
            -m gpt-5 \
            -gpt-engineer-mode codex \
            -g "あなたはPythonプロジェクトのCI修正Botです。error.logを読み取り、適切な修正をdiff形式で出力してください。" \
            -i error.log \
            -o patch.diff

      - name: Apply patch
        run: |
          if [ -s patch.diff ]; then
            git apply patch.diff
          else
            echo "No patch generated."
            exit 1
          fi

      - name: Commit changes to branch
        run: |
          git config user.name "codex-bot"
          git config user.email "codex-bot@example.com"
          branch="codex-fix-$(date +%s)"
          git checkout -b $branch
          git add .
          git commit -m "fix: auto patch by Codex"
          git push origin $branch

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ${{ github.ref }}
          title: "Codex Auto Fix"
          body: "This PR was auto-generated by Codex based on pytest failures. Please review before merge."
          base: main
