name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:  # 手動トリガーも可能

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. チェックアウト
      - uses: actions/checkout@v4

      # 2. Python セットアップ
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. 依存関係インストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
          pip install kaggle

      # 4. Kaggle API 認証設定
      - name: Setup Kaggle API credentials
        run: |
          mkdir -p ~/.kaggle
          echo '${{ secrets.KAGGLE_JSON }}' > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      # 5. Pytest 実行（サンプルデータで動作確認）
      - name: Run tests
        run: pytest -q

      # 6. 本番 Kaggle データで AutoKaggler 実行
      - name: Run AutoKaggler with Kaggle
        run: |
          echo '{"profile":"fast","data_source":"kaggle"}' | python -m autokaggler

      # 7. 生成された submission.csv をアップロード
      - name: Upload submission artifact
        uses: actions/upload-artifact@v4
        with:
          name: submission
          path: .agent_tmp/submissions/*.csv
