name: Kaggle Titanic AutoSubmit

on:
  workflow_dispatch:

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Kaggle
        run: pip install kaggle

      - name: Generate submission (example)
        run: python scripts/train_and_predict.py

      - name: Submit to Kaggle
        run: kaggle competitions submit -c titanic -f data/outputs/submission.csv -m "Auto submit via manual trigger"
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
