name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # リポジトリを取得
      - uses: actions/checkout@v4

      # Python をセットアップ
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # キャッシュ (pip)
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 依存関係インストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]

      # pytest を実行
      - name: Run tests
        run: pytest -q

      # AutoKaggler で submission.csv を生成
      - name: Generate submission.csv
        run: |
          mkdir -p .agent_tmp/submissions
          echo '{"profile": "fast", "data_source": "sample"}' | python -m autokaggler

      # 生成された submission.csv を Artifact として保存
      - name: Upload submission.csv
        uses: actions/upload-artifact@v4
        with:
          name: submission
          path: .agent_tmp/submissions/*.csv
